"""CROSSFIRE CLI entrypoint providing deterministic verification and TCAS telemetry."""

from pathlib import Path
import sys
import click
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from crossfire.detector import detect_collisions
from crossfire.miner import extract_claims
from crossfire.models import CollisionVector, InvariantClaim
from crossfire.resolver import generate_advisory

console = Console()


@click.group()
def cli() -> None:
    """CROSSFIRE: Air Traffic Collision Avoidance System for Parallel AI Agents."""
    pass


@cli.command("verify")
@click.option(
    "--path",
    "-p",
    type=click.Path(exists=True, file_okay=False, dir_okay=True, path_type=Path),
    default=Path("tests/fixtures"),
    help="Directory containing agent scratchpads to verify.",
)
@click.option(
    "--quiet",
    "-q",
    is_flag=True,
    help="Suppress display tables and only return exit code.",
)
def verify(path: Path, quiet: bool) -> None:
    """Run deterministic TCAS collision analysis across subagent scratchpads."""
    files = sorted(path.glob("*.py"))
    agent_a_files = [f for f in files if "agent_a" in f.name.lower()]
    agent_b_files = [f for f in files if "agent_b" in f.name.lower()]

    if not agent_a_files or not agent_b_files:
        console.print(f"[yellow]Warning: Could not find paired agent_a/agent_b scratchpads in {path}[/yellow]")
        sys.exit(0)

    total_collisions: list[CollisionVector] = []
    advisories = []

    for fa in agent_a_files:
        stem_a = fa.stem.replace("agent_a_", "")
        # Find matching agent_b file
        fb_matches = [f for f in agent_b_files if f.stem.replace("agent_b_", "") == stem_a]
        if not fb_matches:
            continue
        fb = fb_matches[0]

        source_a = fa.read_text(encoding="utf-8")
        source_b = fb.read_text(encoding="utf-8")

        claims_a = extract_claims(source_a, agent_id="agent_a")
        claims_b = extract_claims(source_b, agent_id="agent_b")

        cols = detect_collisions(claims_a, claims_b)
        total_collisions.extend(cols)
        for c in cols:
            advisories.append(generate_advisory(c))

    if not quiet:
        console.print("")
        table = Table(
            title="CROSSFIRE TCAS Collision Analysis Report",
            header_style="bold #E8611A",
            border_style="#252525",
        )
        table.add_column("Symbol", style="bold #F0EDE8")
        table.add_column("Collision Class", style="#E8611A")
        table.add_column("Severity", justify="right")
        table.add_column("Target Agent", style="#F5A623")
        table.add_column("Halted", justify="center")

        for adv in advisories:
            col = adv.vector
            halt_str = "[bold red]YES (EXIT 2)[/bold red]" if col.halted else "[green]NO[/green]"
            table.add_row(
                col.claim_a.symbol,
                col.collision_class.upper(),
                f"{col.severity:.2f}",
                adv.target_agent,
                halt_str,
            )

        console.print(table)
        console.print("")

        if advisories:
            last = advisories[-1]
            panel = Panel(
                f"[bold #E8611A]ACTION:[/bold #E8611A] {last.recommended_action}\n"
                f"[bold #F5A623]TARGET AGENT:[/bold #F5A623] {last.target_agent}\n"
                f"[bold #F0EDE8]PATCH HINT:[/bold #F0EDE8]\n[dim]{last.patch_hint}[/dim]",
                title=f"[bold #E8611A]TCAS RESOLUTION ADVISORY: {last.vector.claim_a.symbol}[/bold #E8611A]",
                border_style="#E8611A",
            )
            console.print(panel)

    has_halt = any(c.halted for c in total_collisions)
    if has_halt:
        sys.exit(2)
    sys.exit(0)


@cli.command("report")
def report() -> None:
    """Print the last TCAS Resolution Advisory generated by CROSSFIRE."""
    # Run verification quietly to get the latest advisory
    path = Path("tests/fixtures")
    fa = path / "agent_a_discount.py"
    fb = path / "agent_b_discount.py"
    if fa.exists() and fb.exists():
        claims_a = extract_claims(fa.read_text(encoding="utf-8"), agent_id="agent_a")
        claims_b = extract_claims(fb.read_text(encoding="utf-8"), agent_id="agent_b")
        cols = detect_collisions(claims_a, claims_b)
        if cols:
            adv = generate_advisory(cols[0])
            panel = Panel(
                f"[bold #E8611A]CLASS:[/bold #E8611A] {adv.vector.collision_class.upper()} (Severity: {adv.vector.severity:.2f})\n"
                f"[bold #E8611A]ACTION:[/bold #E8611A] {adv.recommended_action}\n"
                f"[bold #F5A623]TARGET AGENT:[/bold #F5A623] {adv.target_agent}\n"
                f"[bold #F0EDE8]PATCH HINT:[/bold #F0EDE8]\n[dim]{adv.patch_hint}[/dim]",
                title=f"[bold #E8611A]LATEST TCAS ADVISORY: {adv.vector.claim_a.symbol}[/bold #E8611A]",
                border_style="#E8611A",
            )
            console.print(panel)
            return
    console.print("[green]All flight paths clear. No active advisories.[/green]")


def main() -> None:
    """CLI execution wrapper."""
    cli()


if __name__ == "__main__":
    main()
